version: '3.9'
services:
  db:
    image: mongo:5
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: 'form'

  app:
    build: .
    depends_on:
      - 'db'
    volumes:
      - ./:/app
    ports:
      - '5000:5000'
      - '3000:3000'
    environment:
      MONGO_URL: 'mongodb://db:27017/form'
